# Generated by Django 4.2.29 on 2026-06-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
